apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name  : todo-service
          image: jhotwox/todo-service:1.1 # Cambia a la imagen adecuada si usas un registro de imágenes
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/microservicios
          livenessProbe:                     # Liveness Probe
            httpGet:
              path: /                        # Ruta para verificar si está vivo
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo-service
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
