apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: jhotwox/user-service:1.4 # Cambia a la etiqueta, ya sea "latest", "1.1" ... "1.4"
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/microservicios"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
